[project]
name    = "cam"
version = "0.1.0"


std     = "c++17"
cflags = [
    "-D__STDC_CONSTANT_MACROS",
    "-I/usr/include/opencv4",
    "-O3",
]

lflags = [
    "-lavformat",
    "-lavcodec",
    "-lavutil",
    "-lavdevice",
    "-lswscale",
    "-lopencv_imgproc",
    "-lopencv_core",
    "-lopencv_highgui",
]



[dependencies]

