[project]
name    = "cam"
version = "0.1.0"

pkgconfig = ['sdl2']

#std     = "c++17"
cflags = [
    "-g",
    "-O3",
]

lflags = [
    "-g",
    "-lX11",
    "-lGL",
    "-lGLU",
]



[dependencies]
error = "*"
